'use strict';
const F = JSON.parse(document.getElementById('fixture').textContent);
const VIEW = document.body.dataset.view;
const P = new URLSearchParams(location.search);
const views = {import:'Import',library:'Library',map:'Map',skill:'Skill',proposals:'Proposals',usage:'Usage & quality',organization:'Organization'};
const state = P.get('state') || 'ready';
const restricted = state === 'restricted' || (P.has('org') && P.get('org') !== F.org) || (P.has('repo') && P.get('repo') !== F.repo);
const unavailable = restricted || ['degraded','partial','loading','error','empty'].includes(state);
const member = P.get('role') === 'member';
const role = member ? 'member' : 'owner';
const readonly = unavailable || member;
const e = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key = 'guidefold-wireframe-meridian-v1';
let memory = {};
try { memory = JSON.parse(sessionStorage.getItem(key) || '{}'); } catch (_) {}
if(restricted){memory={};try{sessionStorage.removeItem(key);}catch(_){}}
function save(allowMember=false){if(!unavailable && (!member || allowMember)){try{sessionStorage.setItem(key,JSON.stringify(memory));}catch(_){}}}
function url(view, changes={}) {
  const p = new URLSearchParams(P);
  p.set('org','meridian'); p.set('repo','monorepo'); if(restricted)p.set('state','restricted');
  Object.entries(changes).forEach(([k,v])=>v === null ? p.delete(k) : p.set(k,v));
  return `${view}.html?${p.toString()}`;
}
function go(view, changes={}){location.href=url(view,changes);}
function link(view, text, changes={}, cls=''){return `<a ${cls?`class="${cls}"`:''} href="${e(url(view,changes))}">${e(text)}</a>`;}
const disabled = readonly ? 'disabled' : '';
const byId = id => F.skills.find(s=>s.id===id || s.name===id);
const proposalSkill = byId('postgres-auth');
const proposalPrefix = proposalSkill.raw.slice(0,proposalSkill.raw.indexOf(proposalSkill.body));
const selected = byId(P.get('skill')) || proposalSkill;
const partialSkills = [...new Set([proposalSkill,...F.skills.slice(0,7)])];
const dataSkills = state==='partial' ? partialSkills : F.skills;
const sourceURL = path => 'https://github.com/wiatrM/guidefold/blob/'+F.commit+'/examples/monorepo/'+path.split('#')[0];
function sourceLink(path,label){return `<a href="${e(sourceURL(path))}" target="_blank" rel="noopener noreferrer">${e(label || path)} <span class="tiny">(GitHub, new tab)</span></a>`;}
function refs(s){return `<ul class="linklist">${s.references.map(r=>`<li>${sourceLink(r)}${r.includes('#')?`<p class="help">Source fragment: <code>${e(r.split('#')[1])}</code>; no verified line mapping.</p>`:''}</li>`).join('') || '<li>No references declared in the fixture.</li>'}</ul>`;}
function relationList(s){const origin=VIEW==='map'?'map':(['map','library','proposals','usage'].includes(P.get('from'))?P.get('from'):'library'); const axis=VIEW==='map'?(['repository','scopes','pyramid'].includes(P.get('tab'))?P.get('tab'):'repository'):P.get('return_tab');return ['requires','refines'].map(type=>`<div><h3>${type}</h3><ul class="linklist">${s[type].map(id=>`<li>${byId(id)?link('skill',byId(id).name,{skill:id,tab:'source',from:origin,return_tab:axis}):e(id)}<br><small>${e(id)}</small></li>`).join('') || '<li>None declared in source.</li>'}</ul></div>`).join('');}
function metadata(s){const node=F.nodes.find(n=>n.id===s.scope);return `<dl><dt>Repository</dt><dd>${e(F.repo)}</dd><dt>Scope</dt><dd>${e(s.scope)}</dd><dt>Scope paths</dt><dd>${e(node?.paths.join(', ') || 'Unknown')}</dd><dt>Owner from source</dt><dd>${e(s.owner)} (ownership metadata; not an access grant)</dd><dt>Source layer</dt><dd>${e(s.sourceLayer)}</dd><dt>Knowledge layer</dt><dd>Unclassified</dd><dt>Source status</dt><dd>${e(s.sourceStatus)}</dd><dt>Publication</dt><dd>Not established by source status</dd><dt>Source path</dt><dd><code>${e(s.path)}</code></dd><dt>Base commit</dt><dd><code>${e(F.commit)}</code></dd><dt>Content SHA-256</dt><dd><code>${e(s.revision)}</code><br><small>Digest of the exact SKILL.md bytes, including frontmatter.</small></dd></dl>`;}
function tabs(items,current){return `<nav class="tabs" aria-label="${e(views[VIEW])} sections">${items.map(([id,text])=>`<a href="${e(url(VIEW,{tab:id}))}"${current===id?' aria-current="page"':''}>${e(text)}</a>`).join('')}</nav>`;}
function panel(title,content){return `<section class="panel"><h2>${title}</h2>${content}</section>`;}
function note(text){return `<div class="notice" role="status">${text}</div>`;}
function header(){return `<header><div class="brand"><strong>Guidefold <span class="tiny">/ LOW-FI</span></strong><span class="badge">Meridian fixture · Local simulation · No repository writes</span></div></header><div class="shell"><nav class="mainnav" aria-label="Primary">${Object.entries(views).map(([id,label])=>`<a href="${e(url(id))}"${VIEW===id?' aria-current="page"':''}>${label}</a>`).join('')}</nav><main id="main" tabindex="-1"><p class="eyebrow">Stage 4 · interaction wireframe</p><h1>${views[VIEW]}</h1>`;}
function partialManifest(){
 const delivered=new Set(dataSkills.map(s=>s.id));
 const omitted=F.skills.filter(s=>!delivered.has(s.id));
 return `<section class="panel"><h2>Partial QA delivery manifest</h2><p>Identical subset across Import, Library and Map: ${dataSkills.length}/${F.skills.length} skills. All paths below come from the fixture; omission is simulated.</p><details><summary>Delivered source paths (${dataSkills.length})</summary><ul class="linklist">${dataSkills.map(s=>`<li><code>${e(s.path)}</code></li>`).join('')}</ul></details><details><summary>Omitted source paths (${omitted.length})</summary><ul class="linklist">${omitted.map(s=>`<li><code>${e(s.path)}</code></li>`).join('')}</ul></details></section>`;
}
function stateMessage(){
 if(state==='partial')return note(`<strong>Partial · simulated QA subset.</strong> ${dataSkills.length} of ${F.skills.length} fixture skills are delivered; ${F.skills.length-dataSkills.length} are deliberately omitted in this local scenario. This is not an observed import failure. Index age and other source resources are unknown. Base commit: <code>${e(F.commit)}</code>. No deletion or publication is inferred. Changes and export are disabled.`)+(['import','library','map'].includes(VIEW)?partialManifest():'');
 if(state==='degraded')return note('<strong>Degraded · read from the in-memory fixture.</strong> Connection and telemetry are unavailable in this scenario. Changes, export and simulated sync are disabled; source browsing remains available.');
 return '';
}
function blockedView(){
 if(restricted)return panel('Access restricted','<p>This scenario has no authorized organization context. Organization content and locally saved decisions have been cleared from this view.</p><p>Sign in again and request access from an organization owner in the real product. This wireframe does not grant access or authenticate accounts.</p><a class="button primary" href="import.html?org=meridian&amp;repo=monorepo&amp;step=login">Restart fixture sign-in</a><p class="help">Restarts only the local fixture scenario with a cleared context; this is not real authentication.</p>');
 if(state==='loading')return `<section class="panel" aria-busy="true"><h2>Loading ${e(views[VIEW].toLowerCase())}</h2><p role="status">Waiting for a response in this scenario. No result is available yet.</p>${Array(5).fill('<div class="skeleton" aria-hidden="true"></div>').join('')}</section>`;
 if(state==='error')return panel('Unable to load this view',`<p role="alert">The simulated request failed. No import, decision or publication was completed.</p><p>Your current URL context is preserved.</p>${link(VIEW,'Retry local fixture',{state:null},'button primary')}`);
 if(state==='empty'){
 const messages={import:['No repository imported','Choose a provider, create the fixture organization and preview a local import.','Start fixture onboarding','import',{state:null,step:'login'}],library:['No skills available','A complete import makes its existing skills available for browsing.','Open Import','import',{state:null,step:'preview'}],map:['No map available','No skills or scopes are present in this scenario.','Open Import','import',{state:null,step:'preview'}],skill:['No skill selected','Choose a skill from the library to inspect its source and scope.','Open Library','library',{state:null}],proposals:['No proposals to review','This scenario contains no candidates. An absence of proposals is a valid outcome.','Browse sources','library',{state:null}],usage:['No observations','No adapter events or review evidence are available in this scenario. Usefulness and loads are Unknown.','Open Integrations','organization',{state:null,tab:'integrations'}],organization:['No organization selected','Choose a provider and create the local fixture organization.','Start fixture onboarding','import',{state:null,step:'login'}]};
 const [title,body,cta,dest,changes]=messages[VIEW]; return panel(title,`<p>${body}</p>${link(dest,cta,changes,'button primary')}`);
 }
 return null;
}
function render(){
 const blocked=blockedView();
 document.getElementById('app').innerHTML=header()+(restricted?'':`<p class="context">Organization: <strong>meridian</strong> · Repository: <strong>monorepo</strong> · Fixture operator: <strong>${role}</strong> (local test role)<br><small>Role in the URL is a deliberate fixture simulation, not production authentication.${member?' Members can read and leave feedback; import, proposal decisions, export and organization changes require owner.':''}</small></p>`)+(blocked || stateMessage()+({import:renderImport,library:renderLibrary,map:renderMap,skill:renderSkill,proposals:renderProposals,usage:renderUsage,organization:renderOrganization}[VIEW]()))+`<footer class="pagefoot">Local prototype with embedded public fixture data. Authentication, backend, Git review and delivery are not connected. Browser downloads create local files only.</footer></main></div>`;
 if(VIEW==='proposals'&&!blocked){
   const main=document.getElementById('main');
   const decision=main.querySelector('section.panel');
   decision.id='decision';decision.tabIndex=-1;
   main.querySelector('footer').before(decision);
   const entry=document.createElement('a');entry.className='button';entry.href='#decision';entry.textContent=({draft:'Review decision: approve, edit or reject',editing:'Continue editing candidate',approved_for_export:'Continue to export',awaiting_git:'Review Git handoff',published:'Review publication evidence',rejected:'Review rejection reason'}[proposal().stage] || 'Review decision');
   main.querySelector('.row.end').append(entry);
   if(proposal().stage==='published'){
     const evidence=document.createElement('p');evidence.className='context';
     evidence.textContent='Local simulation only · Context loaded: Unknown';
     main.querySelector('.row.end').after(evidence);
   }
 }
 bind();
}
function feedback(text){const t=document.getElementById('feedback');if(t){t.textContent=text;t.setAttribute('role','status');}}
function renderImport(){
 const step=P.get('step') || (memory.imported?'result':memory.org?'preview':memory.login?'organization':'login');
 const stages=['login','organization','preview','result'];
 const intro=`<p class="intro">Preview the permitted source files, then simulate an import. Existing skills become available without an LLM job.</p><ol class="steps">${['Sign in (fixture)','Create organization (fixture)','Preview local manifest','Read the import result'].map((v,i)=>`<li${stages.indexOf(step)===i?' aria-current="step"':''}>${v}${stages.indexOf(step)===i?' — current step':''}</li>`).join('')}</ol>`;
 if(step==='login')return intro+panel('Sign in to the local scenario',`<p>No account is contacted. Choose the provider used by this fixture flow.</p><form id="login-form"><fieldset ${disabled}><legend>Provider</legend><label class="choice"><input type="radio" name="provider" value="Google" checked> Google (fixture)</label><label class="choice"><input type="radio" name="provider" value="GitHub"> GitHub (fixture)</label></fieldset><button class="primary" ${disabled}>Continue with selected provider (fixture)</button></form>`);
 if(step==='organization')return intro+panel('Create the fixture organization',`<p>Signed in as Fixture operator${memory.login?' through '+e(memory.login)+' (simulated)':''}. No real membership is created.</p><form id="org-form"><label for="org-name">Organization name</label><input id="org-name" name="org" value="meridian" readonly><p class="help">Fixed public fixture organization for this local test.</p><button class="primary" ${disabled}>Create meridian (fixture)</button></form>`);
 if(step==='result'&&state==='partial')return intro+panel('Import result · partial QA subset',`<p class="status">Partial · ${dataSkills.length}/${F.skills.length} fixture skills available</p><p>The ${dataSkills.length} delivered source files in the QA manifest are available for reading. ${F.skills.length-dataSkills.length} source paths were deliberately omitted from this scenario. This does not represent a real scan, upload, LLM result or failure.</p><dl><dt>Available scope nodes</dt><dd>${F.nodes.filter(n=>dataSkills.some(s=>s.scope===n.id)).length} of ${F.nodes.length} declared nodes contain delivered skills; any unmapped scope remains explicit.</dd><dt>Base commit</dt><dd><code>${e(F.commit)}</code></dd><dt>Publication</dt><dd>Unavailable · partial QA data cannot activate a snapshot</dd></dl><div class="actionbar">${link('map','Open partial Map',{step:null,tab:'repository'},'button primary')}</div>`);
 if(step==='result')return intro+panel('Import result (fixture)',`<p class="status">Parsed · ready to browse</p><p>${F.skills.length} existing skills and ${F.nodes.length} scope nodes are read from the embedded Meridian fixture. No network upload, scan, LLM generation or publication occurred.</p><dl><dt>Source</dt><dd>examples/monorepo</dd><dt>Commit</dt><dd><code>${e(F.commit)}</code></dd><dt>Publication</dt><dd>Not established · owner review is still required</dd><dt>Ignored sources</dt><dd>Unknown · this fixture contains selected skills only</dd></dl><div class="actionbar">${link('map','Open Map',{step:null,tab:'repository'},'button primary')}</div><p class="help">${link('library','Or open Library',{step:null})}</p>`);
 return intro+panel('Proposed CLI · dry-run preview',`<p>These commands describe the planned product CLI. They are text only and are not executed by this prototype.</p><pre id="commands">guidefold login\nguidefold org use meridian\nguidefold scan . --dry-run\nguidefold import .</pre><div class="row actionbar"><button id="copy-cli">Copy proposed commands</button><span id="copy-status" role="status"></span></div>`)+panel('Local manifest preview',`<p>Organization <strong>meridian</strong> · repository <strong>monorepo</strong>. The manifest below contains the ${dataSkills.length} delivered fixture SKILL.md sources. This is a local preview of selected files, not a completed repository scan.</p><dl><dt>Base commit</dt><dd><code>${e(F.commit)}</code></dd><dt>Source bytes</dt><dd>${dataSkills.reduce((n,s)=>n+s.bytes,0).toLocaleString('en-US')} bytes, from fixture files</dd><dt>Exclusions</dt><dd>Not evaluated in this local simulation. Real dry-run must show ignored files, secrets policy and required assets before upload.</dd></dl><details><summary>Inspect files, hashes and sizes</summary><div class="tablewrap"><table><caption>Selected source manifest</caption><thead><tr><th>Path</th><th>Bytes</th><th>SHA-256</th></tr></thead><tbody>${dataSkills.map(s=>`<tr><td>${e(s.path)}</td><td>${s.bytes}</td><td><code>${e(s.revision)}</code></td></tr>`).join('')}</tbody></table></div></details><p class="help">No repository commands, uploads or LLM calls run. The fixture is already parsed.</p><button id="simulate-import" class="primary" ${disabled}>Simulate import</button><div class="feedback" id="feedback" role="status"></div>`);
}
const values = field => [...new Set(F.skills.map(s=>s[field]))].sort();
function selectField(id,label,options,value,any='All'){return `<div><label for="${id}">${label}</label><select id="${id}" name="${id}"><option value="">${any}</option>${options.map(v=>`<option value="${e(v)}"${v===value?' selected':''}>${e(v)}</option>`).join('')}</select></div>`;}
function renderLibrary(){
 const q=P.get('q')||'';
 const matches=dataSkills.filter(s=>(!q || q.toLowerCase().trim().split(/\s+/).every(word=>`${s.name} ${s.description} ${s.path}`.toLowerCase().includes(word)))&&['scope','owner','layer','status'].every(k=>!P.get(k)||s[{layer:'sourceLayer',status:'sourceStatus'}[k]||k]===P.get(k)));
 return `<p class="intro">Find an instruction, then check its exact source and scope. Source status does not establish publication.</p><form class="filters" id="library-filters"><div><label for="q">Search name, description or path</label><input id="q" name="q" type="search" value="${e(q)}" placeholder="For example: postgres auth"></div>${selectField('scope','Scope',values('scope'),P.get('scope'))}${selectField('owner','Owner from source',values('owner'),P.get('owner'))}${selectField('layer','Source layer',values('sourceLayer'),P.get('layer'))}${selectField('status','Source status',values('sourceStatus'),P.get('status'))}<div class="row"><button class="primary">Apply filters</button>${link('library','Clear filters',{q:null,scope:null,owner:null,layer:null,status:null})}</div></form><p role="status"><strong>${matches.length} skills</strong> match the current filters${state==='partial'?' in the partial snapshot':''}.</p>${matches.length?matches.map(s=>`<article class="skillrow"><h2>${link('skill',s.name,{skill:s.id,tab:'content',from:'library'})}</h2><p>${e(s.description)}</p><p class="tiny">Scope: <strong>${e(s.scope)}</strong> · Owner: ${e(s.owner)} · Source layer: ${e(s.sourceLayer)} · Source status: ${e(s.sourceStatus)} · Knowledge layer: Unclassified</p><code>${e(s.path)}</code></article>`).join(''):panel('No matching skills',`<p>Adjust the search or filters. The underlying fixture has not changed.</p>`)}`;
}
function skillItem(s){return `<li>${link('skill',s.name,{skill:s.id,from:'map',return_tab:P.get('tab')||'repository',tab:'source'})}<br><small>Scope ${e(s.scope)} · Source layer ${e(s.sourceLayer)}</small></li>`;}
function repositoryTree(skills){
 const tree={children:{},skills:[]};
 skills.forEach(s=>{let t=tree;s.path.split('/').slice(0,-1).forEach(folder=>{t.children[folder]??={children:{},skills:[]};t=t.children[folder];});t.skills.push(s);});
 function branch(t,depth=0){return `<ul class="tree">${t.skills.map(skillItem).join('')}${Object.entries(t.children).map(([folder,child])=>`<li><details${depth<2?' open':''}><summary>${e(folder)}/</summary>${branch(child,depth+1)}</details></li>`).join('')}</ul>`;}
 return branch(tree);
}
const scopeNodes = [...F.nodes, ...[...new Set(F.skills.filter(s=>!F.nodes.some(n=>n.id===s.scope)).map(s=>s.scope))].map(id=>({id,paths:['Unknown — no mapping declared in the fixture'],owner:'Unknown — no scope node',unmapped:true}))];
function renderMap(){
 const tab=['repository','scopes','pyramid'].includes(P.get('tab'))?P.get('tab'):'repository';
 let body='';
 if(tab==='repository')body=panel('Repository tree',`<p>Actual fixture paths. Expand directories to reach every imported skill.</p>${repositoryTree(dataSkills)}`);
 if(tab==='scopes')body=panel('Scopes',`<p>Declared scope paths and owners from the fixture. A directory depth is not a knowledge layer.</p>${scopeNodes.filter(n=>state!=='partial'||dataSkills.some(s=>s.scope===n.id)).map(n=>`<details open><summary>${e(n.id)}${n.unmapped?' (unmapped scope)':''} · ${dataSkills.filter(s=>s.scope===n.id).length} skills</summary><p>Paths: <code>${e(n.paths.join(', '))}</code><br>Scope owner: ${e(n.owner)}</p><ul class="tree">${dataSkills.filter(s=>s.scope===n.id).map(skillItem).join('') || '<li>No skill assigned directly to this scope.</li>'}</ul></details>`).join('')}`);
 if(tab==='pyramid')body=panel('Knowledge layer · Unclassified',`<p>The fixture declares source layers (org, platform, team). No atomic/task/abstract classification is provided. Only explicit source relationships are shown below.</p><ul class="tree">${dataSkills.map(skillItem).join('')}</ul><div class="tablewrap"><table><caption>Text alternative: declared knowledge relationships</caption><thead><tr><th>Source skill</th><th>Relationship</th><th>Target skill</th></tr></thead><tbody>${dataSkills.flatMap(s=>['requires','refines'].flatMap(type=>s[type].map(id=>`<tr><td>${link('skill',s.name,{skill:s.id,tab:'dependencies',from:'map',return_tab:'pyramid'})}</td><td>${type}</td><td>${byId(id)?link('skill',byId(id).name,{skill:id,tab:'source',from:'map',return_tab:'pyramid'}):e(id)}</td></tr>`))).join('')}</tbody></table></div>`);
 return `<p class="intro">Explore the source, scope and knowledge axes. Every relationship is declared in the fixture; no similarity or hierarchy is inferred.</p>${tabs([['repository','Repository'],['scopes','Scopes'],['pyramid','Pyramid']],tab)}<div class="two"><div>${body}</div><aside>${panel('Selected skill',`<form id="map-select"><label for="map-skill">Inspect relationships</label><select id="map-skill" name="skill">${dataSkills.map(s=>`<option value="${e(s.id)}"${s.id===selected.id?' selected':''}>${e(s.name)} · ${e(s.scope)}</option>`).join('')}</select><button class="primary actionbar">Select skill</button></form><h3>${e(selected.name)}</h3><p>Source layer: ${e(selected.sourceLayer)}<br>Knowledge layer: Unclassified</p>${link('skill','Open source and scope',{skill:selected.id,tab:'source',from:'map',return_tab:tab})}`)}${panel('Declared relationships',relationList(selected))}</aside></div>`;
}
function renderSkill(){
 const s=byId(P.get('skill')) || proposalSkill;
 if(state==='partial'&&!dataSkills.some(item=>item.id===s.id))return panel('Source omitted from QA subset',`<p>This source file is deliberately omitted from the current 8/27 local snapshot. Its body is unavailable in this scenario.</p>${link('library','Return to partial Library',{},'button primary')}`);
 if(P.get('skill')&&!byId(P.get('skill')))return panel('Skill not found',`<p>The requested identifier is absent from this fixture.</p>${link('library','Return to Library',{},'button primary')}`);
 const tab=['content','source','dependencies','feedback'].includes(P.get('tab'))?P.get('tab'):'content';
 const from=['map','library','proposals','usage'].includes(P.get('from'))?P.get('from'):'library';
 let body='';
 if(tab==='content')body=panel('Original body · source content',`<p>The complete Markdown body is shown as source text. Commands inside it are inert.</p><pre>${e(s.body)}</pre>`);
 if(tab==='source')body=panel('Source and scope',`${metadata(s)}<div class="actionbar">${sourceLink(s.path,'Open exact source revision')}</div><h3>Declared references</h3>${refs(s)}<details><summary>Inspect complete SKILL.md including frontmatter</summary><pre>${e(s.raw)}</pre></details>`);
 if(tab==='dependencies')body=panel('Declared relationships',`<p>These links express source declarations. They do not prove delivery to an agent.</p>${relationList(s)}`);
 if(tab==='feedback')body=panel('Feedback · local note',`<p>No usage observations exist in this fixture. A note is stored only in this browser session and is not telemetry.</p><form id="skill-feedback"><label for="feedback-note">Review note and reason</label><textarea id="feedback-note" name="note" required ${unavailable?'disabled':''}>${e(memory.notes?.[s.id]||'')}</textarea><button class="primary" ${unavailable?'disabled':''}>Save local note</button></form><div id="feedback" class="feedback" role="status"></div>`);
 return `<p class="intro">${link(from,'← Back to '+views[from],{tab:P.get('return_tab')||null,from:null})}</p><h2>${e(s.name)}</h2><p>${e(s.description)}</p><p class="context">Scope: <strong>${e(s.scope)}</strong> · Owner: ${e(s.owner)} · Source status: ${e(s.sourceStatus)}<br><small>Source layer: ${e(s.sourceLayer)} · Knowledge layer: Unclassified · Publication: not established</small></p>${tabs([['content','Content'],['source','Source & scope'],['dependencies','Dependencies'],['feedback','Feedback']],tab)}${body}`;
}
function proposal(){const saved=memory.proposal;return saved?.candidate?.startsWith(proposalPrefix)?saved:{stage:'draft',candidate:proposalSkill.raw,digest:proposalSkill.revision,reason:''};}
function lineDiff(source,candidate){
 const a=source.split('\n'), b=candidate.split('\n');
 let first=0, suffix=0;
 while(first<Math.min(a.length,b.length)&&a[first]===b[first])first++;
 while(suffix<a.length-first&&suffix<b.length-first&&a[a.length-1-suffix]===b[b.length-1-suffix])suffix++;
 const contextBefore=Math.min(2,first), contextAfter=Math.min(2,suffix);
 const start=first-contextBefore;
 const removed=a.slice(first,a.length-suffix), added=b.slice(first,b.length-suffix);
 const before=a.slice(start,first).map(line=>' '+line);
 const after=a.slice(a.length-suffix,a.length-suffix+contextAfter).map(line=>' '+line);
 return [`--- Source: ${proposalSkill.path}`,`+++ Candidate: ${proposalSkill.path}`,`@@ -${start+1},${contextBefore+removed.length+contextAfter} +${start+1},${contextBefore+added.length+contextAfter} @@`,...before,...removed.map(line=>'-'+line),...added.map(line=>'+'+line),...after].join('\n');
}
function renderProposals(){
 const s=proposalSkill, p=proposal();
 const candidate=p.candidate || s.raw;
 const stage=p.stage;
 const stageNames={draft:'Draft',editing:'Editing local candidate',approved_for_export:'Approved for export',awaiting_git:'Awaiting Git',published:'Published (fixture)',rejected:'Rejected (local decision)'};
 let action='';
 if(stage==='draft')action=`<form id="decision-form"><fieldset ${disabled}><legend>Review decision</legend><label class="choice"><input type="radio" name="decision" value="approve" required> Approve for export — prepare the candidate file</label><label class="choice"><input type="radio" name="decision" value="edit" required> Edit candidate — return to a local draft</label><label class="choice"><input type="radio" name="decision" value="reject" required> Reject — close this local proposal with a reason</label></fieldset><label for="decision-reason">Reason for this decision</label><textarea id="decision-reason" name="reason" required ${disabled} placeholder="Explain the source and scope considered.">${e(p.reason)}</textarea><button class="primary" ${disabled}>Record decision (local)</button></form>`;
 if(stage==='editing')action=`<form id="edit-form"><label for="candidate-text">Candidate body · local operator edit</label><textarea id="candidate-text" name="candidate" rows="18" required ${disabled}>${e(candidate.slice(proposalPrefix.length))}</textarea><label for="edit-reason">Reason for the edit</label><textarea id="edit-reason" name="reason" required ${disabled}>${e(p.reason)}</textarea><p class="help">Edit only the Markdown body. Original frontmatter (including scope, owner, source layer and dependencies) is fixed in this fixture. Comparison, SHA-256 and export still include the complete file. Saving returns this candidate to Draft for a new decision.</p><div class="row"><button class="primary" ${disabled}>Save local draft</button><button type="button" id="cancel-edit" ${disabled}>Cancel edit</button></div></form>`;
 if(stage==='approved_for_export')action=`<p>The source file is prepared. This decision does not publish a skill or confirm effectiveness.</p><p>Download creates <code>postgres-auth.SKILL.md</code> with the exact candidate bytes for review against the original source path. It does not write to the repository or create a Git commit.</p><button id="export-patch" class="primary" ${disabled}>Export SKILL.md</button>`;
 if(stage==='awaiting_git')action=`<p><strong>Source file downloaded. Waiting for Git review and sync.</strong> Export alone does not publish the revision.</p><ol class="steps"><li>An operator compares the downloaded source file with the base commit.</li><li>If content changed, the operator reviews and merges those changes in Git. An unchanged source file does not create a new commit.</li><li>A sync verifies the revision and publication policy.</li></ol><p>This prototype cannot observe any of these events. The button below only advances the local scenario; it does not contact Git.</p><button id="simulate-sync" class="primary" ${disabled}>Simulate Git sync</button>`;
 if(stage==='published')action=`<p><strong>Published (fixture)</strong> means this local scenario reached its final state. No Git merge, review, server publication or agent load was verified.</p><dl><dt>Evidence level</dt><dd>Local simulation only</dd><dt>Revision</dt><dd><code>${e(p.digest || s.revision)}</code></dd><dt>Context loaded</dt><dd>Unknown · no adapter observations</dd></dl><div class="actionbar">${link('usage','Check usage evidence',{skill:s.id,scope:s.scope,revision:p.digest || s.revision,from:'proposals'},'button primary')}</div>`;
 if(stage==='rejected')action=`<p>This local candidate was rejected. No export or publication took place.</p><p><strong>Reason:</strong> ${e(p.reason)}</p><button id="reopen-proposal" class="primary" ${disabled}>Reopen as local draft</button>`;
 return `<p class="intro">Review one existing source candidate. This fixture exercise proposes a package of <strong>postgres-auth</strong>; it introduces no new procedure and claims no source problem.</p><div class="row end"><p class="status">${stageNames[stage] || 'Draft'}</p>${link('skill','Inspect source and scope',{skill:s.id,tab:'source',from:'proposals'})}</div><section class="panel"><h2>Decision and publication</h2><p class="help">Author: source fixture · Viewer: Fixture operator (${role} role in this local scenario). Decisions require owner.</p><p class="help">Draft → Approved for export → Awaiting Git → Published (fixture). Each step is separate.</p>${action}${p.reason&&!['draft','editing','rejected'].includes(stage)?`<p class="help"><strong>Decision reason:</strong> ${e(p.reason)}</p>`:''}<div class="feedback" id="feedback" role="status"></div></section>${candidate===s.raw?'':panel('Line diff · local body edits',`<p><code>+</code> added lines · <code>−</code> removed lines. Frontmatter remains fixed. This comparison is for review; export downloads the complete SKILL.md file.</p><pre id="candidate-diff" class="rawbox" tabindex="0" aria-label="Source to candidate line diff">${e(lineDiff(s.raw,candidate))}</pre>`)}<div class="two"><section class="panel"><h2>Source · exact imported revision</h2><p>Owner: ${e(s.owner)}<br>Scope: ${e(s.scope)}<br>Source layer: ${e(s.sourceLayer)} · Knowledge layer: Unclassified<br>Source status: ${e(s.sourceStatus)} · publication at import: not established</p><p><code>${e(s.path)}</code></p><p class="tiny">Commit: <code>${e(F.commit)}</code><br>SHA-256: <code>${e(s.revision)}</code></p>${sourceLink(s.path,'Open source in Git')}<details><summary>Declared references</summary>${refs(s)}</details><details><summary>Full original SKILL.md</summary><pre class="rawbox" tabindex="0" aria-label="Original source text">${e(s.raw)}</pre></details></section><section class="panel"><h2>Candidate · ${candidate===s.raw?'unchanged source':'operator-edited local draft'}</h2><p class="status">${candidate===s.raw?'No text changes':'Text changed by local operator'}</p><p>Same scope: ${e(s.scope)}<br>Same source owner: ${e(s.owner)}<br>Source layer: ${e(s.sourceLayer)} · Knowledge layer: Unclassified</p><p class="tiny">Candidate SHA-256: <code>${e(p.digest || s.revision)}</code></p><p class="help">${candidate===s.raw?'The full source text is copied exactly into the proposed package.':'Compare the complete candidate with the source alongside it; export contains only this local candidate.'}</p><details><summary>Full candidate SKILL.md</summary><pre class="rawbox" tabindex="0" aria-label="Candidate source text">${e(candidate)}</pre></details></section></div>`;
}
function renderUsage(){
 return `<p class="intro">Start with a reason and its evidence. This source fixture contains no adapter events, feedback episodes or verified publication records.</p><section class="panel"><h2>Review queue</h2><p class="status">No observations</p><p>No evidence-backed review items can be derived from this fixture. Missing telemetry does not prove a skill is unused or incorrect.</p><div class="tablewrap"><table><caption>Reason-driven review queue</caption><thead><tr><th>Skill and revision</th><th>Reason</th><th>Evidence</th><th>Owner action</th></tr></thead><tbody><tr><td colspan="4">No observed items. A real item needs a source change, removal or feedback event before offering Checked, Fixed in Git or No change with reason.</td></tr></tbody></table></div><div class="actionbar">${link('organization','Inspect integration setup',{tab:'integrations'},'button primary')}</div></section><section class="panel"><h2>Observation context</h2><form id="usage-filters" class="filters">${selectField('scope','Scope',values('scope'),P.get('scope'))}<div><label for="usage-skill">Skill</label><select id="usage-skill" name="skill"><option value="">All fixture skills</option>${F.skills.map(s=>`<option value="${e(s.id)}"${P.get('skill')===s.id?' selected':''}>${e(s.name)}</option>`).join('')}</select></div><div><label for="revision">Revision</label><input id="revision" name="revision" value="${e(P.get('revision')||'')}" placeholder="Optional SHA-256"></div><div><label for="harness">Harness</label><select id="harness" name="harness"><option value="">Unknown · no events</option></select></div><button>Apply observation filters</button></form><p>Window: Unknown · Source: no event ledger · Observation coverage: Unknown.</p><div class="tablewrap"><table><caption>Delivery and outcome evidence</caption><thead><tr><th>Measure</th><th>Value</th><th>Why</th></tr></thead><tbody>${[['Card exposures','No adapter delivery events'],['download_verified','No checksum/download events'],['context_loaded','No adapter acknowledgement'],['Applied: reported / observed','No attributed task episodes'],['Helpfulness','No helped/hindered assessments; denominator unavailable'],['Feedback coverage','No eligible episode identifiers'],['Integration lag or losses','No connection health observations']].map(([metric,why])=>`<tr><th scope="row">${metric}</th><td>Unknown</td><td>${why}</td></tr>`).join('')}</tbody></table></div><p class="help">Published and loaded are separate. A download or HTTP success would not prove the instruction reached the model context.</p></section>`;
}
function renderOrganization(){
 const tab=P.get('tab')==='integrations'?'integrations':'members';
 let body='';
 if(tab==='members')body=panel('Members',`<p>Only the test operator is supplied. Source owner strings name teams in fixture metadata and are not member accounts.</p><div class="tablewrap"><table><caption>Local membership scenario</caption><thead><tr><th>Member</th><th>Role</th><th>Access</th><th>Action</th></tr></thead><tbody><tr><td>Fixture operator <small>(synthetic role)</small></td><td>${member?'Member':'Owner'}</td><td>All permitted fixture repositories</td><td>${member?'Removal unavailable: owner required':'Removal unavailable: last owner'}</td></tr>${(memory.members||[]).map((m,i)=>`<tr><td>${e(m)} <small>(local entry)</small></td><td>Member</td><td>Simulated only</td><td><button data-remove-member="${i}" ${disabled}>Remove local entry</button></td></tr>`).join('')}</tbody></table></div><form id="invite-form" class="actionbar"><label for="member-label">Member label for local simulation</label><input id="member-label" name="member" maxlength="80" required ${disabled} placeholder="Enter a test label"><p class="help">No email address is required. No invitation is sent; this creates a local entry only.</p><button class="primary" ${disabled}>Simulate member invitation</button></form><div class="feedback" id="feedback" role="status"></div>`)+panel('Organization boundary',`<dl><dt>Organization</dt><dd>meridian (fixture)</dd><dt>Repository</dt><dd>monorepo</dd><dt>Permission model</dt><dd>Owner/member scenario; CODEOWNERS and source owner metadata do not authorize access.</dd><dt>Organization switching</dt><dd>Only one fixture organization is available. A foreign org/repo URL shows Restricted without organization content.</dd></dl>`);
 if(tab==='integrations')body=panel('Install an adapter · Proposed CLI',`<p>Commands below are proposed product syntax. This prototype does not install or contact a harness.</p><label for="adapter">Adapter scenario</label><select id="adapter"><option value="claude">Claude Code</option><option value="copilot">Copilot CLI</option></select><pre id="adapter-command">guidefold install --harness claude\nguidefold doctor</pre><div class="row actionbar"><button id="copy-adapter">Copy proposed commands</button><button id="simulate-connection" class="primary" ${disabled}>Simulate connection check</button></div><div class="feedback" id="feedback" role="status">${memory.connection?'Local check complete. Actual adapter connection and delivery remain Unknown.':''}</div>`)+panel('Connection and token evidence',`<dl><dt>Repository / org</dt><dd>monorepo / meridian</dd><dt>Installation scope</dt><dd>Unknown · no adapter configuration</dd><dt>Adapter connection</dt><dd>Unknown · not connected</dd><dt>download_verified</dt><dd>Unknown · no observations</dd><dt>context_loaded</dt><dd>Unknown · no observations</dd><dt>Version / capabilities</dt><dd>Unknown · no adapter handshake</dd><dt>Tokens</dt><dd>No real tokens are available or issued by this wireframe.</dd></dl><details><summary>Local token lifecycle exercise</summary><p>This stores a boolean scenario state only; no credential is generated.</p><button id="simulate-token" ${disabled}>${memory.token?'Simulate token revocation':'Simulate token creation'}</button><p class="help">Scenario token: ${memory.token?'present (no credential value)':'absent'}.</p></details>`);
 return `<p class="intro">Inspect organization access and adapter setup. All changes below are local simulations.</p>${tabs([['members','Members'],['integrations','Integrations']],tab)}${body}`;
}
async function copyText(id,statusId='feedback'){
 const el=document.getElementById(id), statusEl=document.getElementById(statusId);
 try{await navigator.clipboard.writeText(el.textContent);if(statusEl)statusEl.textContent='Copied text only. No command was executed.';}
 catch(_){const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);if(statusEl)statusEl.textContent='Copy is unavailable here. The command text is selected; use your browser Copy action.';}
}
function mutating(handler,allowMember=false){return async event=>{event.preventDefault();if(unavailable || (member && !allowMember))return;await handler(event);};}
function on(id,event,fn){const el=document.getElementById(id);if(el)el.addEventListener(event,fn);}
function recordFilters(id,fields){on(id,'submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);go(VIEW,Object.fromEntries(fields.map(field=>[field,data.get(field)||null])));});}
function downloadPatch(){
 const p=proposal(), text=p.candidate || proposalSkill.raw;
 const blob=new Blob([text],{type:'text/markdown;charset=utf-8'}), href=URL.createObjectURL(blob), a=document.createElement('a');
 a.href=href;a.download='postgres-auth.SKILL.md';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000);
 memory.proposal={...p,stage:'awaiting_git'};save();render();document.getElementById('decision')?.focus();
}

function bind(){
 if(restricted || ['loading','error','empty'].includes(state))return;
 on('login-form','submit',mutating(event=>{memory.login=new FormData(event.currentTarget).get('provider');save();go('import',{step:'organization'});}));
 on('org-form','submit',mutating(()=>{memory.org=true;save();go('import',{step:'preview'});}));
 on('simulate-import','click',mutating(()=>{memory.imported=true;save();go('import',{step:'result'});}));
 on('copy-cli','click',()=>copyText('commands','copy-status'));
 recordFilters('library-filters',['q','scope','owner','layer','status']);
 recordFilters('usage-filters',['scope','skill','revision','harness']);
 on('map-select','submit',event=>{event.preventDefault();go('map',{skill:new FormData(event.currentTarget).get('skill')});});
 on('skill-feedback','submit',mutating(event=>{const reason=new FormData(event.currentTarget).get('note').trim();if(!reason)return;memory.notes??={};memory.notes[selected.id]=reason;save(true);feedback('Local note saved for this revision. No telemetry was sent.');},true));
 on('decision-form','submit',mutating(event=>{const data=new FormData(event.currentTarget),reason=data.get('reason').trim(),decision=data.get('decision');if(!reason || !decision)return;memory.proposal={...proposal(),reason,stage:{approve:'approved_for_export',edit:'editing',reject:'rejected'}[decision]};save();render();document.getElementById('decision')?.focus();}));
 on('edit-form','submit',mutating(async event=>{const data=new FormData(event.currentTarget), body=data.get('candidate'),candidate=proposalPrefix+body,reason=data.get('reason').trim();if(!body.trim()||!reason)return;const bytes=new TextEncoder().encode(candidate);const hash=await crypto.subtle.digest('SHA-256',bytes);const digest=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');memory.proposal={stage:'draft',candidate,digest,reason};save();render();}));
 on('cancel-edit','click',mutating(()=>{memory.proposal={...proposal(),stage:'draft'};save();render();}));
 on('export-patch','click',mutating(downloadPatch));
 on('simulate-sync','click',mutating(()=>{if(proposal().stage!=='awaiting_git')return;memory.proposal={...proposal(),stage:'published'};save();render();}));
 on('reopen-proposal','click',mutating(()=>{memory.proposal={...proposal(),stage:'draft'};save();render();}));
 on('invite-form','submit',mutating(event=>{const value=new FormData(event.currentTarget).get('member').trim();if(!value)return;memory.members??=[];memory.members.push(value);save();render();feedback('Local member entry created. No invitation was sent.');}));
 document.querySelectorAll('[data-remove-member]').forEach(button=>button.addEventListener('click',mutating(()=>{memory.members.splice(Number(button.dataset.removeMember),1);save();render();feedback('Local member entry removed. No real access changed.');})));
 on('adapter','change',event=>{document.getElementById('adapter-command').textContent='guidefold install --harness '+event.target.value+'\nguidefold doctor';});
 on('copy-adapter','click',()=>copyText('adapter-command'));
 on('simulate-connection','click',mutating(()=>{memory.connection=true;save();feedback('Local check complete. Actual adapter connection and delivery remain Unknown.');}));
 on('simulate-token','click',mutating(()=>{memory.token=!memory.token;save();render();feedback('Token lifecycle simulated. No credential was issued or revoked.');}));
}
render();



