{{- include "gf.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gf.configName" . }}
  labels:
    {{- include "gf.labels" . | nindent 4 }}
immutable: true
data:
  {{- include "gf.configData" . | nindent 2 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gf.name" . }}
  labels:
    {{- include "gf.labels" . | nindent 4 }}
automountServiceAccountToken: false
