import {chromium, expect} from '@playwright/test';
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out=path.join(root,'qa');
await mkdir(out,{recursive:true});
const fixture=JSON.parse(await readFile(path.join(root,'src/data/fixture.json'),'utf8'));
const source=fixture.skills.find(s=>s.name==='postgres-auth');
const prefix=source.raw.match(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n)+/)[0];
const sha=s=>createHash('sha256').update(s).digest('hex');
const origin=process.env.GUIDEFOLD_UI_URL||'http://127.0.0.1:4331';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const checks=[];
const url=(view,params={})=>origin+'/'+view+'?'+new URLSearchParams({org:'meridian',repo:'monorepo',...params});
async function check(name,fn){try{const evidence=await fn();checks.push({name,pass:true,...evidence});}catch(e){checks.push({name,pass:false,error:e.message});throw e;}}
let edited, editedHash;
try {
 await check('source Markdown is semantic; raw file remains exact and keyboard decision jump works',async()=>{
  await page.goto(url('proposals'));
  await page.getByText('Read source body',{exact:true}).click();
  await expect(page.getByRole('heading',{name:'postgres-auth',exact:true})).toHaveCount(1);
  const contentHeadings=await page.locator('details[open] h3, details[open] h4, details[open] h5').count();
  expect(contentHeadings).toBeGreaterThan(0);
  await page.getByText('Full original SKILL.md · raw file',{exact:true}).click();
  expect(await page.getByLabel('Original SKILL.md source text',{exact:true}).textContent()).toBe(source.raw);
  const jump=page.getByRole('link',{name:'Jump to decision and publication',exact:true}).first();
  await jump.focus();await page.keyboard.press('Enter');
  await expect(page.locator('#decision')).toBeFocused();
  await page.screenshot({path:path.join(out,'flow-decision-keyboard.png')});
  return {headings:contentHeadings,sourceSHA256:sha(source.raw),sourceBytes:Buffer.byteLength(source.raw)};
 });
 await check('owner edits only body, reviews exact full-file diff and records a fresh approval',async()=>{
  await page.locator('input[name=decision][value=edit]').check();
  await page.locator('#decision-reason').fill('Review source and scope before adjusting cache guidance.');
  await page.getByRole('button',{name:'Record decision (local)',exact:true}).click();
  await expect(page.locator('#candidate-text')).toBeVisible();
  const body=await page.locator('#candidate-text').inputValue();
  expect(prefix+body).toBe(source.raw);
  const needle='30';
  expect(body).toContain(needle);
  const editedBody=body.replace('30','60');
  edited=prefix+editedBody;editedHash=sha(edited);
  await page.locator('#candidate-text').fill(editedBody);
  await page.locator('#edit-reason').fill('Increase the local candidate cache interval from 30 to 60; fixture-only edit.');
  await page.getByRole('button',{name:'Save local draft',exact:true}).click();
  await expect(page.locator('#decision-form')).toBeVisible();
  const candidateDigest=await page.locator('body').textContent();
  expect(candidateDigest).toContain(editedHash);
  await expect(page.getByText('Text changed by local operator',{exact:true})).toBeVisible();
  const diff=await page.getByLabel('Source to candidate line diff',{exact:true}).textContent();
  const removedLine=body.split('\n').find(line=>line.includes('30'));
  expect(diff).toContain('− '+removedLine);
  expect(diff).toContain('+ '+removedLine.replace('30','60'));
  await page.locator('input[name=decision][value=approve]').check();
  await page.locator('#decision-reason').fill('Reviewed full file, declared scope and source evidence for this local candidate.');
  await page.getByRole('button',{name:'Record decision (local)',exact:true}).click();
  await expect(page.locator('#export-patch')).toBeEnabled();
  await page.screenshot({path:path.join(out,'flow-edited-approved.png'),fullPage:true});
  return {candidateSHA256:editedHash,frontmatterUnchanged:edited.startsWith(prefix)};
 });
 await check('export retains exact candidate bytes and enters Awaiting Git before fixture sync',async()=>{
  const pending=page.waitForEvent('download');
  await page.locator('#export-patch').click();
  const download=await pending;
  const downloadPath=path.join(out,'flow-postgres-auth.SKILL.md');
  await download.saveAs(downloadPath);
  const bytes=await readFile(downloadPath);
  expect(bytes.equals(Buffer.from(edited))).toBe(true);
  expect(sha(bytes)).toBe(editedHash);
  expect(bytes.subarray(0,Buffer.byteLength(prefix)).equals(Buffer.from(prefix))).toBe(true);
  await expect(page.locator('#simulate-sync')).toBeVisible();
  expect(await page.getByRole('link',{name:'Check usage evidence',exact:true}).count()).toBe(0);
  const stageBefore=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('guidefold-ui-meridian-v1')).proposal.stage);
  expect(stageBefore).toBe('awaiting_git');
  await page.locator('#simulate-sync').click();
  await expect(page.getByRole('link',{name:'Check usage evidence',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('guidefold-ui-meridian-v1')).proposal.stage)).toBe('published');
  return {filename:download.suggestedFilename(),bytes:bytes.length,sha256:sha(bytes),stageBeforeSync:stageBefore,stageAfterSync:'published fixture'};
 });
 await check('usage preserves exact candidate context and unavailable source revision cannot masquerade as imported body',async()=>{
  await page.getByRole('link',{name:'Check usage evidence',exact:true}).click();
  const params=new URL(page.url()).searchParams;
  expect(params.get('skill')).toBe(source.id);expect(params.get('scope')).toBe(source.scope);expect(params.get('revision')).toBe(editedHash);
  await expect(page.locator('#revision')).toHaveValue(editedHash);
  await page.getByRole('link',{name:'Inspect postgres-auth',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Selected revision unavailable',exact:true})).toBeVisible();
  expect(await page.getByRole('heading',{name:'Original body',exact:true}).count()).toBe(0);
  expect(await page.locator('#feedback-note').count()).toBe(0);
  await page.getByRole('link',{name:'Back to Usage & quality',exact:true}).click();
  await expect(page.locator('#revision')).toHaveValue(editedHash);
  await page.getByRole('link',{name:'Inspect postgres-auth',exact:true}).click();
  await page.getByRole('link',{name:'Open available imported revision',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Original body',exact:true})).toBeVisible();
  expect(new URL(page.url()).searchParams.get('revision')).toBe(source.revision);
  await page.screenshot({path:path.join(out,'flow-imported-revision.png')});
  return {selectedCandidateSHA256:editedHash,availableSourceSHA256:source.revision,bodyBlockedUntilExplicitRevisionChange:true};
 });
 await check('source and two dependency hops retain Map axis and imported-revision source identity',async()=>{
  const startSkill=fixture.skills.find(s=>s.name==='turnstile-oncall-runbook');
  await page.goto(url('map',{tab:'scopes',skill:startSkill.id}));
  await page.getByRole('link',{name:'Open source and scope',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Source and scope',exact:true})).toBeVisible();
  expect(new URL(page.url()).searchParams.get('return_tab')).toBe('scopes');
  const gitHref=await page.getByRole('link',{name:'Open exact source revision',exact:false}).first().getAttribute('href');
  expect(gitHref).toBe('https://github.com/wiatrM/guidefold/blob/'+fixture.commit+'/examples/monorepo/'+startSkill.path);
  await page.getByText('Inspect complete SKILL.md including frontmatter',{exact:true}).click();
  const rawSource=page.getByLabel('Complete imported SKILL.md',{exact:true});
  expect(await rawSource.textContent()).toBe(startSkill.raw);
  await rawSource.focus();await expect(rawSource).toBeFocused();
  const hops=[];
  let current=startSkill;
  for(let n=0;n<2;n++){
   await page.getByRole('link',{name:'Dependencies',exact:true}).click();
   const nextId=current.requires[0]||current.refines[0];
   expect(nextId).toBeTruthy();
   current=fixture.skills.find(s=>s.id===nextId);
   await page.getByRole('link',{name:current.name,exact:true}).first().click();
   expect(new URL(page.url()).searchParams.get('revision')).toBe(current.revision);
   await expect(page.getByRole('heading',{name:'Source and scope',exact:true})).toBeVisible();
   hops.push(current.name);
  }
  await page.getByRole('link',{name:'Back to Map',exact:true}).click();
  expect(new URL(page.url()).searchParams.get('tab')).toBe('scopes');
  await expect(page.getByRole('heading',{name:'Declared scopes',exact:true})).toBeVisible();
  return {hops,returnedAxis:'scopes',sourceLink:gitHref,sourceLinkHasExactHostPathAndCommit:true};
 });
 await check('member can save local revision feedback but cannot decide or export',async()=>{
  await page.goto(url('skill',{role:'member',skill:source.id,revision:source.revision,tab:'feedback'}));
  await page.locator('#feedback-note').fill('Member fixture note: verify scope before use.');
  await page.getByRole('button',{name:'Save local note',exact:true}).click();
  await expect(page.getByText('Local note saved for this revision. No telemetry was sent.',{exact:true})).toBeVisible();
  const before=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('guidefold-ui-meridian-v1')).proposal);
  await page.goto(url('proposals',{role:'member'}));
  expect(await page.locator('#export-patch').count()).toBe(0);
  const after=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('guidefold-ui-meridian-v1')).proposal);
  expect(after).toEqual(before);
  await page.evaluate(()=>sessionStorage.removeItem('guidefold-ui-meridian-v1'));
  await page.reload();
  await expect(page.locator('input[name=decision][value=approve]')).toBeDisabled();
  await expect(page.locator('#decision-reason')).toBeDisabled();
  await expect(page.getByRole('button',{name:'Record decision (local)',exact:true})).toBeDisabled();
  await page.goto(url('proposals'));
  await page.locator('input[name=decision][value=approve]').check();
  await page.locator('#decision-reason').fill('Owner approves exact source for testing member export protection.');
  await page.getByRole('button',{name:'Record decision (local)',exact:true}).click();
  await expect(page.locator('#export-patch')).toBeEnabled();
  await page.goto(url('proposals',{role:'member'}));
  await expect(page.locator('#export-patch')).toBeDisabled();
  expect(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('guidefold-ui-meridian-v1')).proposal.stage)).toBe('approved_for_export');
  await page.evaluate(()=>sessionStorage.removeItem('guidefold-ui-meridian-v1'));
  return {feedbackAllowed:true,decisionDisabled:true,approvedCandidateExportDisabled:true};
 });
 for(const state of ['partial','degraded']){
  await check(state+' preserves source reading and blocks mutations',async()=>{
   await page.goto(url('proposals',{state}));
   await expect(page.locator('input[name=decision][value=approve]')).toBeDisabled();
   await expect(page.locator('#decision-reason')).toBeDisabled();
   await page.getByText('Read source body',{exact:true}).click();
   expect(await page.locator('details[open] h3, details[open] h4, details[open] h5').count()).toBeGreaterThan(0);
   await page.goto(url('skill',{state,skill:source.id,tab:'feedback'}));
   await expect(page.locator('#feedback-note')).toBeDisabled();
   await expect(page.getByRole('button',{name:'Save local note',exact:true})).toBeDisabled();
   if(state==='partial'){
    const delivered=[source,...fixture.skills.filter(s=>s.id!==source.id).slice(0,7)];
    const omitted=fixture.skills.find(s=>!delivered.some(d=>d.id===s.id));
    await page.goto(url('skill',{state,skill:omitted.id}));
    await expect(page.getByRole('heading',{name:'Source omitted from QA subset',exact:true})).toBeVisible();
    expect(await page.getByRole('heading',{name:'Original body',exact:true}).count()).toBe(0);
   }
   return {sourceReadable:true,mutationsDisabled:true,omittedSourceBodyBlocked:state==='partial'};
  });
 }
 await check('rejection is a human decision with a retained reason and a route back to Draft',async()=>{
  await page.goto(url('proposals'));
  await page.locator('input[name=decision][value=reject]').check();
  await page.locator('#decision-reason').fill('Local candidate needs a scope review before export.');
  await page.getByRole('button',{name:'Record decision (local)',exact:true}).click();
  const badge=page.getByText('Rejected (local decision)',{exact:true});
  await expect(badge).toBeVisible();
  const classes=await badge.getAttribute('class');
  expect(classes).not.toContain('error');
  await expect(page.locator('p').filter({hasText:'Reason: Local candidate needs a scope review before export.'})).toBeVisible();
  await page.getByRole('button',{name:'Reopen as local draft',exact:true}).click();
  await expect(page.locator('#decision-form')).toBeVisible();
  return {errorColorNotUsed:true,reasonPreserved:true,reopenToDraft:true};
 });
} catch(e) {
 console.error(e.message);
} finally {
 const report={date:new Date().toISOString(),kind:'Local fixture browser regression; not human pilot or production proof',source:{skill:source.id,path:source.path,sha256:source.revision,bytes:source.bytes},checks,jsErrors:errors,passed:checks.every(c=>c.pass)&&checks.length===9&&errors.length===0};
 await writeFile(path.join(out,'owner-flow.json'),JSON.stringify(report,null,2)+'\n');
 await browser.close();
 console.log(JSON.stringify(report,null,2));
 if(!report.passed)process.exitCode=1;
}
